[package]
name = "winrangle"
version = "0.1.0"
authors = ["Brad Alexander <balexander@instartlogic.com>"]
edition = "2018"

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
livesplit-hotkey = "0.4.0"
parking_lot = "0.8"
